name: Pull Requests

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@dfaf4c006776de6a4d162f557e5566c75fa3e96c # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
